#!/bin/sh

cd ../work

LN="ln -fs"
RM="rm"

$RM Makefile ini_itr.F90 sav_itr.F90 drv_str.F90 cns_str.F90 cnv_ctv.F90 cnv_ctv_ad.F90 cnv_inn.F90 costf.F90 \
ctl_str.F90 def_cov.F90 def_coef.F90 def_coef_bc.F90 def_grd.F90 def_nml.F90 eof_str.F90 int_par.F90 \
int_obs_hor.F90 get_obs.F90 get_obs_arg.F90 get_obs_sla.F90 get_obs_xbt.F90 get_obs_gld.F90 grd_str.F90 \
get_obs_sst.F90 obs_sst.F90 obs_sst_ad.F90 rdmxd.F90 def_loc.F90 \
ini_cfn.F90 ini_nrm.F90 min_cfn.F90 obs_arg.F90 obs_arg_ad.F90 obs_sla.F90 obs_sla_ad.F90 obs_str.F90 \
obs_xbt.F90 obs_xbt_ad.F90 obs_gld.F90 obs_gld_ad.F90 obsop.F90 obsop_ad.F90 rcfl_1.F90 rcfl_1_ad.F90 \
rcfl_2.F90 rcfl_2_ad.F90 rcfl_x.F90 rcfl_x_ad.F90 rcfl_y.F90 rcfl_y_ad.F90 rdgrd.F90 rdeofs.F90 res_inc.F90 \
resid.F90 routines.F set_knd.F90 oceanvar.F90 veof.F90 veof_ad.F90 ver_hor.F90 ver_hor_ad.F90 wrt_dia.F90 \
obs_vec.F90 bar_mod.F90 bmd_str.F90 get_byg.F90 get_byg_ad.F90 ini_bmd.F90 invrt.F90 bar_mod_ad.F90 invrt_ad.F90 \
get_vel.F90 get_vel_ad.F90 div_dmp.F90 div_dmp_ad.F90 get_obs_tra.F90 obs_tra.F90 obs_tra_ad.F90 get_obs_trd.F90 \
obs_trd.F90 obs_trd_ad.F90 mod_trj_ad.F90 mod_trj_tl.F90 get_obs_vdr.F90 obs_vdr.F90 obs_vdr_ad.F90 \
get_obs_gvl.F90 obs_gvl.F90 obs_gvl_ad.F90 netcdf_err.F90 mpi_str.F90 def_mpid.F90 exc_mpi.F90 sav_msf.F90 \
mod_msf.F90 mod_inc.F90

$LN ../src/Makefile Makefile
$LN ../src/structures/set_knd.F90 set_knd.F90
$LN ../src/structures/drv_str.F90 drv_str.F90
$LN ../src/structures/cns_str.F90 cns_str.F90
$LN ../src/structures/ctl_str.F90 ctl_str.F90
$LN ../src/structures/eof_str.F90 eof_str.F90
$LN ../src/structures/grd_str.F90 grd_str.F90
$LN ../src/structures/obs_str.F90 obs_str.F90
$LN ../src/observations/get_obs.F90 get_obs.F90
$LN ../src/observations/get_obs_arg.F90 get_obs_arg.F90
$LN ../src/observations/get_obs_sla.F90 get_obs_sla.F90
$LN ../src/observations/get_obs_xbt.F90 get_obs_xbt.F90
$LN ../src/observations/get_obs_gld.F90 get_obs_gld.F90
$LN ../src/observations/get_obs_vdr.F90 get_obs_vdr.F90
$LN ../src/observations/get_obs_gvl.F90 get_obs_gvl.F90
$LN ../src/observations/get_obs_sst.F90 get_obs_sst.F90
$LN ../src/observations/int_par.F90 int_par.F90
$LN ../src/observations/obs_vec.F90 obs_vec.F90
$LN ../src/observations/get_obs_tra.F90 get_obs_tra.F90
$LN ../src/observations/get_obs_trd.F90 get_obs_trd.F90
$LN ../src/observations/int_obs_hor.F90 int_obs_hor.F90
$LN ../src/initialise/netcdf_err.F90 netcdf_err.F90
$LN ../src/initialise/def_cov.F90 def_cov.F90
$LN ../src/initialise/def_coef.F90 def_coef.F90
$LN ../src/initialise/def_coef_bc.F90 def_coef_bc.F90
$LN ../src/initialise/def_grd.F90 def_grd.F90
$LN ../src/initialise/def_nml.F90 def_nml.F90
$LN ../src/initialise/ini_cfn.F90 ini_cfn.F90
$LN ../src/initialise/rdgrd.F90 rdgrd.F90
$LN ../src/initialise/rdeofs.F90 rdeofs.F90
$LN ../src/initialise/ini_itr.F90 ini_itr.F90
$LN ../src/initialise/rdmxd.F90 rdmxd.F90
$LN ../src/initialise/def_loc.F90 def_loc.F90
$LN ../src/minimize/costf.F90 costf.F90
$LN ../src/minimize/min_cfn.F90 min_cfn.F90
$LN ../src/minimize/res_inc.F90 res_inc.F90
$LN ../src/minimize/resid.F90 resid.F90
$LN ../src/minimize/routines.F routines.F
$LN ../src/minimize/ini_nrm.F90 ini_nrm.F90
$LN ../src/obs_operator/obs_arg.F90 obs_arg.F90
$LN ../src/obs_operator/obs_arg_ad.F90 obs_arg_ad.F90
$LN ../src/obs_operator/obs_sla.F90 obs_sla.F90
$LN ../src/obs_operator/obs_sla_ad.F90 obs_sla_ad.F90
$LN ../src/obs_operator/obs_xbt.F90 obs_xbt.F90
$LN ../src/obs_operator/obs_xbt_ad.F90 obs_xbt_ad.F90
$LN ../src/obs_operator/obs_gld.F90 obs_gld.F90
$LN ../src/obs_operator/obs_gld_ad.F90 obs_gld_ad.F90
$LN ../src/obs_operator/obs_vdr.F90 obs_vdr.F90
$LN ../src/obs_operator/obs_gvl.F90 obs_gvl.F90
$LN ../src/obs_operator/obs_vdr_ad.F90 obs_vdr_ad.F90
$LN ../src/obs_operator/obs_gvl_ad.F90 obs_gvl_ad.F90
$LN ../src/obs_operator/obs_tra.F90 obs_tra.F90
$LN ../src/obs_operator/obs_tra_ad.F90 obs_tra_ad.F90
$LN ../src/obs_operator/obs_trd.F90 obs_trd.F90
$LN ../src/obs_operator/obs_trd_ad.F90 obs_trd_ad.F90
$LN ../src/obs_operator/obs_sst.F90 obs_sst.F90
$LN ../src/obs_operator/obs_sst_ad.F90 obs_sst_ad.F90
$LN ../src/obs_operator/obsop.F90 obsop.F90
$LN ../src/obs_operator/obsop_ad.F90 obsop_ad.F90
$LN ../src/postproc/cnv_inn.F90 cnv_inn.F90
$LN ../src/postproc/sav_itr.F90 sav_itr.F90
$LN ../src/postproc/wrt_dia.F90 wrt_dia.F90
$LN ../src/postproc/mod_inc.F90 mod_inc.F90
$LN ../src/transformation/cnv_ctv.F90 cnv_ctv.F90
$LN ../src/transformation/cnv_ctv_ad.F90 cnv_ctv_ad.F90
$LN ../src/transformation/rcfl_1.F90 rcfl_1.F90
$LN ../src/transformation/rcfl_1_ad.F90 rcfl_1_ad.F90
$LN ../src/transformation/rcfl_2.F90 rcfl_2.F90
$LN ../src/transformation/rcfl_2_ad.F90 rcfl_2_ad.F90
$LN ../src/transformation/rcfl_x.F90 rcfl_x.F90
$LN ../src/transformation/rcfl_x_ad.F90 rcfl_x_ad.F90
$LN ../src/transformation/rcfl_y.F90 rcfl_y.F90
$LN ../src/transformation/rcfl_y_ad.F90 rcfl_y_ad.F90
$LN ../src/transformation/veof.F90 veof.F90
$LN ../src/transformation/veof_ad.F90 veof_ad.F90
$LN ../src/transformation/ver_hor.F90 ver_hor.F90
$LN ../src/transformation/ver_hor_ad.F90 ver_hor_ad.F90
$LN ../src/transformation/get_vel.F90 get_vel.F90
$LN ../src/transformation/div_dmp.F90 div_dmp.F90
$LN ../src/transformation/get_vel_ad.F90 get_vel_ad.F90
$LN ../src/transformation/div_dmp_ad.F90 div_dmp_ad.F90
$LN ../src/oceanvar.F90 oceanvar.F90
$LN ../src/barmod/bar_mod.F90 bar_mod.F90
$LN ../src/barmod/bmd_str.F90 bmd_str.F90
$LN ../src/barmod/get_byg.F90 get_byg.F90
$LN ../src/barmod/get_byg_ad.F90 get_byg_ad.F90
$LN ../src/barmod/ini_bmd.F90 ini_bmd.F90
$LN ../src/barmod/invrt.F90 invrt.F90
$LN ../src/barmod/bar_mod_ad.F90 bar_mod_ad.F90
$LN ../src/barmod/invrt_ad.F90 invrt_ad.F90
$LN ../src/trjmodel/mod_trj_tl.F90 mod_trj_tl.F90
$LN ../src/trjmodel/mod_trj_ad.F90 mod_trj_ad.F90
$LN ../src/mpi/mpi_str.F90 mpi_str.F90
$LN ../src/mpi/def_mpid.F90 def_mpid.F90
$LN ../src/mpi/exc_mpi.F90 exc_mpi.F90
$LN ../src/observations/sav_msf.F90 sav_msf.F90
$LN ../src/observations/mod_msf.F90 mod_msf.F90
